// create mock data

const { query } = require('../../index');

const uid = 'NYGP0wlOEhSU7BYZi0yZPBwHqNN2';

const feedbacksArray = [
  {
    bootcamperuid: uid,
    coachname: 'Tao',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 1,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'Ben',
    feedbackdate: '2020-12-04',
    subject: 'react',
    week: 2,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Liz',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 3,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'James',
    feedbackdate: '2020-12-04',
    subject: 'css',
    week: 4,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Mell',
    feedbackdate: '2020-12-05',
    subject: 'css',
    week: 5,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Tao',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 6,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'Ben',
    feedbackdate: '2020-12-04',
    subject: 'react',
    week: 7,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Liz',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 8,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'James',
    feedbackdate: '2020-12-04',
    subject: 'css',
    week: 9,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Mell',
    feedbackdate: '2020-12-05',
    subject: 'css',
    week: 10,
    type: 'mastery',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Tao',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 1,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'Ben',
    feedbackdate: '2020-12-04',
    subject: 'react',
    week: 2,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Liz',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 3,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'James',
    feedbackdate: '2020-12-04',
    subject: 'css',
    week: 4,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Mell',
    feedbackdate: '2020-12-05',
    subject: 'css',
    week: 5,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Tao',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 6,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'Ben',
    feedbackdate: '2020-12-04',
    subject: 'react',
    week: 7,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Liz',
    feedbackdate: '2020-11-18',
    subject: 'react',
    week: 8,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-11-15',
    datesubmitted: '2020-11-15',
  },
  {
    bootcamperuid: uid,
    coachname: 'James',
    feedbackdate: '2020-12-04',
    subject: 'css',
    week: 9,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
  {
    bootcamperuid: uid,
    coachname: 'Mell',
    feedbackdate: '2020-12-05',
    subject: 'css',
    week: 10,
    type: 'recap',
    passedtests: 7,
    totaltests: 10,
    qualitative: "(coach's comment)",
    duedate: '2020-12-02',
    datesubmitted: '2020-12-01',
  },
];

const sqlStatement = `
    INSERT INTO feedback
        (bootcamperuid, coachname, feedbackdate, subject, week, type, passedtests, totaltests, qualitative, duedate, datesubmitted)
    VALUES
        ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
;`;
// doesnt like feedback, not sure why
// --> add "const" before feedback on line 80, need to drop and create table again and try to populate!
// i have no permmission to use terminal tho..

async function populateTable() {
  let feedbackDataArray;
  for (const feedback of feedbacksArray) {
    console.log(feedback);
    feedbackDataArray = Object.values(feedback);
    console.log(feedbackDataArray);
    await query(sqlStatement, feedbackDataArray);
  }
}

populateTable();
