function demoData(uid) {
  return [
    {
      bootcamperuid: uid,
      coachname: 'Tao',
      feedbackdate: '2020-11-18',
      subject: 'React',
      week: 1,
      type: 'mastery',
      passedtests: 9,
      totaltests: 10,
      qualitative:
        'Your understanding of custom hooks in React is really good, well done.',
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'Ben',
      feedbackdate: '2020-12-04',
      subject: 'JS',
      week: 2,
      type: 'mastery',
      passedtests: 4,
      totaltests: 10,
      qualitative:
        'A good start.  As a general tip, you might want to use Codewars to help you improve with breaking down problems and the syntax of functions.',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Liz',
      feedbackdate: '2020-11-18',
      subject: 'CSS',
      week: 3,
      type: 'mastery',
      passedtests: 10,
      totaltests: 10,
      qualitative:
        "Wow! I remember you saying you have a creative background, it's great to see that translated into code.",
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'James',
      feedbackdate: '2020-12-04',
      subject: 'Node.js',
      week: 4,
      type: 'mastery',
      passedtests: 6,
      totaltests: 10,
      qualitative:
        "Good work but don't forget to install all the dependencies you need!  That probably would have helped you on question 3.  Otherwise good stuff, more practice will help consolidate what you've learnt.",
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Mell',
      feedbackdate: '2020-12-05',
      subject: 'HTML',
      week: 5,
      type: 'mastery',
      passedtests: 8,
      totaltests: 10,
      qualitative:
        'Great knowledge of HTML, which will give you a great starting point in your knowledge for all the other languages and frameworks you are yet to learn.',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Tao',
      feedbackdate: '2020-11-18',
      subject: 'Next.js',
      week: 6,
      type: 'mastery',
      passedtests: 4,
      totaltests: 10,
      qualitative:
        "After using create-react-app comfortably, it can be a big change to switch to using Next.js as your React framework. With a bit of research and practice, you'll be able to confidently utilise all the benefits Next.js provides such as SSR and file-based routing system. Keep persevering!",
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'Ben',
      feedbackdate: '2020-12-04',
      subject: 'React',
      week: 7,
      type: 'mastery',
      passedtests: 5,
      totaltests: 10,
      qualitative:
        'You should try the tasks again to improve your skills in using React, especially the question about handing down props.  It can be difficult to get your head around it but with practice I promise it will be straightforward!',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Liz',
      feedbackdate: '2020-11-18',
      subject: 'React',
      week: 8,
      type: 'mastery',
      passedtests: 9,
      totaltests: 10,
      qualitative:
        'Really well done! Just have another go at the useReducer question.',
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'James',
      feedbackdate: '2020-12-04',
      subject: 'Gatsby',
      week: 9,
      type: 'mastery',
      passedtests: 5,
      totaltests: 10,
      qualitative:
        "Don't feel overwhelmed, Gatsby is a adjustment to learn. But the docs are useful, do check them out.",
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Mell',
      feedbackdate: '2020-12-05',
      subject: 'SQL',
      week: 10,
      type: 'mastery',
      passedtests: 10,
      totaltests: 10,
      qualitative: 'Your SQL knowledge is amazing! Keep it up.',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Tao',
      feedbackdate: '2020-11-18',
      subject: 'The DOM',
      week: 1,
      type: 'recap',
      passedtests: 6,
      totaltests: 10,
      qualitative:
        'A good effort, especially with the first two tasks. MDN should help you with task 3 when you have time to review it.',
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'Ben',
      feedbackdate: '2020-12-04',
      subject: 'HTML Canvas',
      week: 2,
      type: 'recap',
      passedtests: 4,
      totaltests: 10,
      qualitative:
        "I know design isn't a priority for you, but it is an important part of being a rounded developer, so when you have time you should review this task.",
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Liz',
      feedbackdate: '2020-11-18',
      subject: 'Component libraries',
      week: 3,
      type: 'recap',
      passedtests: 8,
      totaltests: 10,
      qualitative: 'Well done, this is really good work here.',
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'James',
      feedbackdate: '2020-12-04',
      subject: 'Authentication',
      week: 4,
      type: 'recap',
      passedtests: 5,
      totaltests: 10,
      qualitative:
        "I know you used Auth0 last week so that probably explains why you struggled more with Firebase, but it's important to be comfortable with a variety of tools so I suggest you spend some time looking at the docs.",
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Mell',
      feedbackdate: '2020-12-05',
      subject: 'SQL',
      week: 5,
      type: 'recap',
      passedtests: 3,
      totaltests: 10,
      qualitative:
        'Good effort - I know the SQL syntax is new to you and it can be a pain. Come to the after school club this week if you can so we can go through this together.',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Tao',
      feedbackdate: '2020-11-18',
      subject: 'Serverless',
      week: 6,
      type: 'recap',
      passedtests: 8,
      totaltests: 10,
      qualitative:
        'Very impressed, especially as Serverless and Yaml were new technologies and syntax for you to use. Keep up the good work!',
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'Ben',
      feedbackdate: '2020-12-04',
      subject: 'useContext',
      week: 7,
      type: 'recap',
      passedtests: 10,
      totaltests: 10,
      qualitative:
        'Really impressed with your knowledge here, looking forward to seeing you use useContext in your hackathons and projects!',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Liz',
      feedbackdate: '2020-11-18',
      subject: 'React Hooks',
      week: 8,
      type: 'recap',
      passedtests: 8,
      totaltests: 10,
      qualitative:
        "You're on the right track, and I can see that you've got the knowledge of useState and useReducer, however it's just the small syntax errors getting in your way. Have a look over them, and the best way to remember syntax is practice.",
      duedate: '2020-11-15',
      datesubmitted: '2020-11-15',
    },
    {
      bootcamperuid: uid,
      coachname: 'James',
      feedbackdate: '2020-12-04',
      subject: 'Express.js',
      week: 9,
      type: 'recap',
      passedtests: 10,
      totaltests: 10,
      qualitative:
        "Wow, you've really impressed me here with your knowledge of the backend and using Express as a Node.js framework",
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
    {
      bootcamperuid: uid,
      coachname: 'Mell',
      feedbackdate: '2020-12-05',
      subject: 'JS',
      week: 10,
      type: 'recap',
      passedtests: 1,
      totaltests: 10,
      qualitative:
        'We should discuss where this went wrong, and how you can improve for next time. Come to one of the Tuesday or Wednesday evening help sessions this week.',
      duedate: '2020-12-02',
      datesubmitted: '2020-12-01',
    },
  ];
}

module.exports = { demoData };
